learning_templates/basic_app/urls.py
from basic_app import views
from django.conf.urls import url,include

#Template Tagging
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100,'number2':99}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load my_extras %}
  {% block body_block %}
    <h1>Welcome to index!</h1>
    <h1>This is index.html!</h1>
    <h1>{{ text|cut1:'world' }}</h1>
    <h1>{{ number|add:'69' }}</h1>
    <h1>{{ number|add:number2 }}</h1>

  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
  {% block body_block %}
    <h1>Welcome to other!</h1>
    <h2>This is an example of template inheritence</h2>
  {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'basic_app:other' %}">The OTHER Page</a>
    <p></p>
    <a href="{% url 'admin:index' %}">Link to Admin</a>
    <p></p>
    <a href="{% url 'index' %}">Link to index</a>

  </body>
</html>